name: release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v3
    - name: build
      run: |
        make crossbuild
    - name: upload
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: dist/*
    - uses: haya14busa/action-update-semver@v1
      with:
        major_version_tag_only: true
