name: tagpr

on:
  push:
    branches:
    - "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v3
    - name: tagpr
      run: |
        make install
        echo '::echo::on'
        tagpr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
